// source: grpc/adm_dto/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.adm_dto.AllServiceStatusDto', null, global);
goog.exportSymbol('proto.adm_dto.OnlineServiceInfoDto', null, global);
goog.exportSymbol('proto.adm_dto.ServiceInfoDto', null, global);
goog.exportSymbol('proto.adm_dto.ServiceStatusDto', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adm_dto.ServiceInfoDto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adm_dto.ServiceInfoDto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.adm_dto.ServiceInfoDto.displayName = 'proto.adm_dto.ServiceInfoDto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adm_dto.OnlineServiceInfoDto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adm_dto.OnlineServiceInfoDto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.adm_dto.OnlineServiceInfoDto.displayName = 'proto.adm_dto.OnlineServiceInfoDto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adm_dto.ServiceStatusDto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.adm_dto.ServiceStatusDto.repeatedFields_, null);
};
goog.inherits(proto.adm_dto.ServiceStatusDto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.adm_dto.ServiceStatusDto.displayName = 'proto.adm_dto.ServiceStatusDto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adm_dto.AllServiceStatusDto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.adm_dto.AllServiceStatusDto.repeatedFields_, null);
};
goog.inherits(proto.adm_dto.AllServiceStatusDto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.adm_dto.AllServiceStatusDto.displayName = 'proto.adm_dto.AllServiceStatusDto';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adm_dto.ServiceInfoDto.prototype.toObject = function(opt_includeInstance) {
  return proto.adm_dto.ServiceInfoDto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adm_dto.ServiceInfoDto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.ServiceInfoDto.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tag: jspb.Message.getFieldWithDefault(msg, 2, ""),
    introduce: jspb.Message.getFieldWithDefault(msg, 3, ""),
    serviceIcon: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adm_dto.ServiceInfoDto}
 */
proto.adm_dto.ServiceInfoDto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adm_dto.ServiceInfoDto;
  return proto.adm_dto.ServiceInfoDto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adm_dto.ServiceInfoDto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adm_dto.ServiceInfoDto}
 */
proto.adm_dto.ServiceInfoDto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntroduce(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceIcon(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adm_dto.ServiceInfoDto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adm_dto.ServiceInfoDto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adm_dto.ServiceInfoDto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.ServiceInfoDto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIntroduce();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getServiceIcon();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.adm_dto.ServiceInfoDto.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.adm_dto.ServiceInfoDto} returns this
 */
proto.adm_dto.ServiceInfoDto.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string tag = 2;
 * @return {string}
 */
proto.adm_dto.ServiceInfoDto.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.adm_dto.ServiceInfoDto} returns this
 */
proto.adm_dto.ServiceInfoDto.prototype.setTag = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string introduce = 3;
 * @return {string}
 */
proto.adm_dto.ServiceInfoDto.prototype.getIntroduce = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.adm_dto.ServiceInfoDto} returns this
 */
proto.adm_dto.ServiceInfoDto.prototype.setIntroduce = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string service_icon = 4;
 * @return {string}
 */
proto.adm_dto.ServiceInfoDto.prototype.getServiceIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.adm_dto.ServiceInfoDto} returns this
 */
proto.adm_dto.ServiceInfoDto.prototype.setServiceIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.toObject = function(opt_includeInstance) {
  return proto.adm_dto.OnlineServiceInfoDto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adm_dto.OnlineServiceInfoDto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.OnlineServiceInfoDto.toObject = function(includeInstance, msg) {
  var f, obj = {
    endpointHost: jspb.Message.getFieldWithDefault(msg, 1, ""),
    endpointPort: jspb.Message.getFieldWithDefault(msg, 2, 0),
    applicationVersion: jspb.Message.getFieldWithDefault(msg, 3, ""),
    applicationVersionNum: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adm_dto.OnlineServiceInfoDto}
 */
proto.adm_dto.OnlineServiceInfoDto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adm_dto.OnlineServiceInfoDto;
  return proto.adm_dto.OnlineServiceInfoDto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adm_dto.OnlineServiceInfoDto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adm_dto.OnlineServiceInfoDto}
 */
proto.adm_dto.OnlineServiceInfoDto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndpointHost(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEndpointPort(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationVersion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setApplicationVersionNum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adm_dto.OnlineServiceInfoDto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adm_dto.OnlineServiceInfoDto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.OnlineServiceInfoDto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEndpointHost();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEndpointPort();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getApplicationVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getApplicationVersionNum();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * optional string endpoint_host = 1;
 * @return {string}
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.getEndpointHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.adm_dto.OnlineServiceInfoDto} returns this
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.setEndpointHost = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 endpoint_port = 2;
 * @return {number}
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.getEndpointPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.adm_dto.OnlineServiceInfoDto} returns this
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.setEndpointPort = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string application_version = 3;
 * @return {string}
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.getApplicationVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.adm_dto.OnlineServiceInfoDto} returns this
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.setApplicationVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 application_version_num = 4;
 * @return {number}
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.getApplicationVersionNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.adm_dto.OnlineServiceInfoDto} returns this
 */
proto.adm_dto.OnlineServiceInfoDto.prototype.setApplicationVersionNum = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.adm_dto.ServiceStatusDto.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adm_dto.ServiceStatusDto.prototype.toObject = function(opt_includeInstance) {
  return proto.adm_dto.ServiceStatusDto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adm_dto.ServiceStatusDto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.ServiceStatusDto.toObject = function(includeInstance, msg) {
  var f, obj = {
    info: (f = msg.getInfo()) && proto.adm_dto.ServiceInfoDto.toObject(includeInstance, f),
    onlineInfoListList: jspb.Message.toObjectList(msg.getOnlineInfoListList(),
    proto.adm_dto.OnlineServiceInfoDto.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adm_dto.ServiceStatusDto}
 */
proto.adm_dto.ServiceStatusDto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adm_dto.ServiceStatusDto;
  return proto.adm_dto.ServiceStatusDto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adm_dto.ServiceStatusDto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adm_dto.ServiceStatusDto}
 */
proto.adm_dto.ServiceStatusDto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.adm_dto.ServiceInfoDto;
      reader.readMessage(value,proto.adm_dto.ServiceInfoDto.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    case 2:
      var value = new proto.adm_dto.OnlineServiceInfoDto;
      reader.readMessage(value,proto.adm_dto.OnlineServiceInfoDto.deserializeBinaryFromReader);
      msg.addOnlineInfoList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adm_dto.ServiceStatusDto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adm_dto.ServiceStatusDto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adm_dto.ServiceStatusDto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.ServiceStatusDto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.adm_dto.ServiceInfoDto.serializeBinaryToWriter
    );
  }
  f = message.getOnlineInfoListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.adm_dto.OnlineServiceInfoDto.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServiceInfoDto info = 1;
 * @return {?proto.adm_dto.ServiceInfoDto}
 */
proto.adm_dto.ServiceStatusDto.prototype.getInfo = function() {
  return /** @type{?proto.adm_dto.ServiceInfoDto} */ (
    jspb.Message.getWrapperField(this, proto.adm_dto.ServiceInfoDto, 1));
};


/**
 * @param {?proto.adm_dto.ServiceInfoDto|undefined} value
 * @return {!proto.adm_dto.ServiceStatusDto} returns this
*/
proto.adm_dto.ServiceStatusDto.prototype.setInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.adm_dto.ServiceStatusDto} returns this
 */
proto.adm_dto.ServiceStatusDto.prototype.clearInfo = function() {
  return this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.adm_dto.ServiceStatusDto.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated OnlineServiceInfoDto online_info_list = 2;
 * @return {!Array<!proto.adm_dto.OnlineServiceInfoDto>}
 */
proto.adm_dto.ServiceStatusDto.prototype.getOnlineInfoListList = function() {
  return /** @type{!Array<!proto.adm_dto.OnlineServiceInfoDto>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.adm_dto.OnlineServiceInfoDto, 2));
};


/**
 * @param {!Array<!proto.adm_dto.OnlineServiceInfoDto>} value
 * @return {!proto.adm_dto.ServiceStatusDto} returns this
*/
proto.adm_dto.ServiceStatusDto.prototype.setOnlineInfoListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.adm_dto.OnlineServiceInfoDto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.adm_dto.OnlineServiceInfoDto}
 */
proto.adm_dto.ServiceStatusDto.prototype.addOnlineInfoList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.adm_dto.OnlineServiceInfoDto, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.adm_dto.ServiceStatusDto} returns this
 */
proto.adm_dto.ServiceStatusDto.prototype.clearOnlineInfoListList = function() {
  return this.setOnlineInfoListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.adm_dto.AllServiceStatusDto.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adm_dto.AllServiceStatusDto.prototype.toObject = function(opt_includeInstance) {
  return proto.adm_dto.AllServiceStatusDto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adm_dto.AllServiceStatusDto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.AllServiceStatusDto.toObject = function(includeInstance, msg) {
  var f, obj = {
    allServiceStatusListList: jspb.Message.toObjectList(msg.getAllServiceStatusListList(),
    proto.adm_dto.ServiceStatusDto.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adm_dto.AllServiceStatusDto}
 */
proto.adm_dto.AllServiceStatusDto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adm_dto.AllServiceStatusDto;
  return proto.adm_dto.AllServiceStatusDto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adm_dto.AllServiceStatusDto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adm_dto.AllServiceStatusDto}
 */
proto.adm_dto.AllServiceStatusDto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.adm_dto.ServiceStatusDto;
      reader.readMessage(value,proto.adm_dto.ServiceStatusDto.deserializeBinaryFromReader);
      msg.addAllServiceStatusList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adm_dto.AllServiceStatusDto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adm_dto.AllServiceStatusDto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adm_dto.AllServiceStatusDto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.adm_dto.AllServiceStatusDto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllServiceStatusListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.adm_dto.ServiceStatusDto.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ServiceStatusDto all_service_status_list = 1;
 * @return {!Array<!proto.adm_dto.ServiceStatusDto>}
 */
proto.adm_dto.AllServiceStatusDto.prototype.getAllServiceStatusListList = function() {
  return /** @type{!Array<!proto.adm_dto.ServiceStatusDto>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.adm_dto.ServiceStatusDto, 1));
};


/**
 * @param {!Array<!proto.adm_dto.ServiceStatusDto>} value
 * @return {!proto.adm_dto.AllServiceStatusDto} returns this
*/
proto.adm_dto.AllServiceStatusDto.prototype.setAllServiceStatusListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.adm_dto.ServiceStatusDto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.adm_dto.ServiceStatusDto}
 */
proto.adm_dto.AllServiceStatusDto.prototype.addAllServiceStatusList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.adm_dto.ServiceStatusDto, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.adm_dto.AllServiceStatusDto} returns this
 */
proto.adm_dto.AllServiceStatusDto.prototype.clearAllServiceStatusListList = function() {
  return this.setAllServiceStatusListList([]);
};


goog.object.extend(exports, proto.adm_dto);
